{{- $fullName := .Values.ingress.name -}}
{{- $svcName := .Values.service.name -}}
{{- $svcPort := .Values.service.port -}}
{{- $connectfullName := .Values.kafka.connect.name -}}
{{- $connectsvcPort := .Values.kafka.connect.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "foobar-gamestop.labels" . | nindent 4 }}
    alb.ingress.kubernetes.io/name: {{ $fullName }}
  annotations:
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    # share a single ALB with all ingress rules with search-app-ingress
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: {{ $fullName }}
    nginx.ingress.kubernetes.io/rewrite-target: /
  {{- end }}
spec:
  rules:
  - http:
      paths:
      - path: /connectors/*
        pathType: Prefix
        backend:
          serviceName: {{ $connectfullName }}-service
          servicePort: {{ $connectsvcPort }}
      - path: /app
        backend:
          serviceName: {{ $svcName }}
          servicePort: {{ $svcPort }}
      # - path:
      #   backend:
      #     serviceName: {{ .Release.Name }}-cassandra
      #     servicePort: 9042
          
      
